# Generated by Django 6.0.6 on 2026-06-29 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPengunjung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kuesioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengunjung', models.CharField(max_length=100)),
                ('tanggal_kunjungan', models.DateField()),
                ('kualitas_layanan', models.IntegerField()),
                ('fasilitas', models.IntegerField()),
                ('kebersihan', models.IntegerField()),
                ('saran', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jenis_pengunjung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan.jenispengunjung')),
            ],
        ),
    ]
